spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/calch}
    username: ${DATASOURCE_USERNAME:xxx}
    password: ${DATASOURCE_PASSWORD:xxx.}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    initialization-mode: always
    hikari:
      idle-timeout: 600000
      connection-timeout: 30000

jwt:
  secretKey: vj7/hMQe+EryZ/3V4O8MjT6Vib1FEivj1xwxIZTam4M=

logging:
  level:
    org:
      springframework:
        security: DEBUG