spring:
  datasource:
    url: jdbc:mysql://localhost:3306/a9i-savings
    username: richardroj
    password: Coki447.
    driver-class-name: com.mysql.cj.jdbc.Driver
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    initialization-mode: always
