package com.ajustadoati.sc.domain.enums;

public enum TransactionType {
  SAVING,
  SHARED_CONTRIBUTION,
  ADMINISTRATIVE,
  SUPPLIES,
  LOAN_INTEREST_PAYMENT,
  LOAN_PAYMENT,
    DISTRIBUTED_INTEREST,
  OTHER_PAYMENTS,
  WHEELS,
  WITHDRAWAL,
  PAYMENT_REVERSAL;

}
